version: "3.8"

services:
  postgresql:
    image: postgres:${DB__TAG:-14-alpine}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB__NAME:-vault}
      POSTGRES_USER: ${DB__USER:-vault}
      POSTGRES_PASSWORD: ${DB__PASS:?database password required}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: vaultwarden/server:${VAULT__TAG:-latest}
    restart: unless-stopped
    ports:
      - "${VAULT__PORT_HTTP:-9011}:80"
      - "${VAULT__PORT_WS:-9012}:3012"
    environment:
      DATABASE_URL: postgresql://${DB__USER:-vault}:${DB__PASS}@postgresql:5432/${DB__NAME:-vault}
      ADMIN_TOKEN: ${VAULT__ADMIN_TOKEN:?admin token required}
    env_file:
      - .env
    volumes:
      - ./data/server:/data
    depends_on:
      - db

  db-backup: # Backups handled by https://github.com/tiredofit/docker-db-backup
    image: tiredofit/db-backup:latest
    tmpfs:
      - /tmp
    volumes:
      - ./data/db-backups:/backup
    environment:
      DB_TYPE: pgsql
      DB_HOST: postgresql
      DB_NAME: ${DB__NAME:-vault}
      DB_USER: ${DB__USER:-vault}
      DB_PASS: ${DB__PASS}
      DB_DUMP_FREQ: ${DB__BACKUP_DUMP_FREQ:-1440}
      DB_DUMP_BEGIN: ${DB__BACKUP_DUMP_BEGIN:-0300}
      DB_CLEANUP_TIME: ${DB__BACKUP_CLEANUP_TIME:-10080}
      CHECKSUM: ${DB__BACKUP_CHECKSUM:-SHA1}
      COMPRESSION: ${DB__BACKUP_COMPRESSION:-ZSTD}
    restart: unless-stopped
    depends_on:
      - postgresql

volumes:
  database:
    driver: local
